Roles + migration bugs, WIP
SqlException: The DELETE statement conflicted with the REFERENCE constraint "FK_Likes_DllFiles_DllFileId". The conflict occurred in database "aspnet-SCPSLPluginBrowser-f4844a68-e75f-4eca-8a76-ec3f0df3c296", table "dbo.Likes", column 'DllFileId'.